apiVersion: networking.linode.com/alpha1v1
kind: CloudFirewall
metadata:
  name: default
  namespace: kube-system
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-weight": "-5"
    
spec:
  firewall-id: "930680"
