---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: kube-system
  labels:
    {{- include "cloud-firewall-controller.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount -}}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
